// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSN0INXY7JlERSG7F30S8D7xqIZkQ4-_k',
    appId: '1:819360492367:web:e6190b33e8789da5b0b33a',
    messagingSenderId: '819360492367',
    projectId: 'book-shelf-920bb',
    authDomain: 'book-shelf-920bb.firebaseapp.com',
    storageBucket: 'book-shelf-920bb.appspot.com',
    measurementId: 'G-1KDP6LDF0B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1EWqJeewuvTjdauVa40DS5qofAvDOX3U',
    appId: '1:819360492367:android:968e4abbb5a305f8b0b33a',
    messagingSenderId: '819360492367',
    projectId: 'book-shelf-920bb',
    storageBucket: 'book-shelf-920bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEN1Zk_acsRtlzaNIyWyWFR-D3AHCxh5s',
    appId: '1:819360492367:ios:85830cbb3e1ecdf6b0b33a',
    messagingSenderId: '819360492367',
    projectId: 'book-shelf-920bb',
    storageBucket: 'book-shelf-920bb.appspot.com',
    androidClientId: '819360492367-22lh6go1t68752di31uo2s1n1ttg9unt.apps.googleusercontent.com',
    iosClientId: '819360492367-6h91fo0hl3gekon0kuqkis4ugfeuba3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookShelf',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEN1Zk_acsRtlzaNIyWyWFR-D3AHCxh5s',
    appId: '1:819360492367:ios:c878cee99513bd03b0b33a',
    messagingSenderId: '819360492367',
    projectId: 'book-shelf-920bb',
    storageBucket: 'book-shelf-920bb.appspot.com',
    androidClientId: '819360492367-22lh6go1t68752di31uo2s1n1ttg9unt.apps.googleusercontent.com',
    iosClientId: '819360492367-dpf84kvmp62p6l6h10dhtd2o5flv0suu.apps.googleusercontent.com',
    iosBundleId: 'com.example.bookShelf.RunnerTests',
  );
}
